"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from glob import glob
import syncplay
from syncplay.product import BUNDLE_IDENTIFIER, PRODUCT_NAME

APP = ['syncplayClient.py']
DATA_FILES = [
    ('resources', glob('syncplay/resources/*.png') + glob('syncplay/resources/*.rtf') + glob('syncplay/resources/*.txt') + glob('syncplay/resources/*.lua')),
    ('resources/lua/intf', glob('syncplay/resources/lua/intf/*.lua'))
]
OPTIONS = {
    'iconfile': 'syncplay/resources/icon.icns',
    'extra_scripts': 'syncplayServer.py',
    'includes': {'PySide6.QtCore', 'PySide6.QtGui', 'PySide6.QtWidgets', 'certifi', 'cffi', 'pem', 'charset_normalizer.md__mypyc'},
    'excludes': {'PySide', 'PySide2', 'PySide.QtCore', 'PySide.QtUiTools', 'PySide.QtGui', 'tkinter'},
    'arch': 'universal2',
    'qt_plugins': [
        'platforms/libqcocoa.dylib',
        'platforms/libqminimal.dylib',
        'platforms/libqoffscreen.dylib',
        'styles/libqmacstyle.dylib'
    ],
    'plist': {
        'CFBundleName': PRODUCT_NAME,
        'CFBundleDisplayName': PRODUCT_NAME,
        'CFBundleShortVersionString': syncplay.version,
        'CFBundleVersion': syncplay.version,
        'CFBundleIdentifier': BUNDLE_IDENTIFIER,
        'LSMinimumSystemVersion': '13.0',
        'NSHumanReadableCopyright': '{} is based on Syncplay and licensed under Apache 2.0.'.format(PRODUCT_NAME),
    }
}

setup(
    app=APP,
    name=PRODUCT_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
